services:
  mfc_parser:
    build:
      context: ./mfc_parser
      dockerfile: Dockerfile.mfc_parser
    container_name: mfc_parser
    expose:
      - "5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  mfc_backend:
    build:
      context: ./mfc_backend
      dockerfile: Dockerfile.mfc_backend
    container_name: mfc_backend
    ports:
      - "8000:8000"
    depends_on:
      - mfc_parser
    env_file:
      - .env

  celery:
    build:
      context: ./mfc_parser
      dockerfile: Dockerfile.celery
    container_name: celery
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    container_name: db
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - ${REDIS_PORT}

volumes:
  postgres_data:
